<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DV" failures="2" tests="13" name="Test" time="0.384" errors="0" timestamp="2021-05-27T12:51:04 IST">
  <testcase classname="testng.sample.TestcasesTest" name="testtopassTest3" time="0.043"/>
  <testcase classname="testng.sample.TestcasesTest" name="testtopassTest4" time="0.07"/>
  <testcase classname="testng.sample.TestcasesTest" name="testtofailTest1" time="0.081">
    <skipped/>
  </testcase> <!-- testtofailTest1 -->
  <testcase classname="testng.sample.TestcasesTest" name="testtofailTest2" time="0.089">
    <skipped/>
  </testcase> <!-- testtofailTest2 -->
  <testcase classname="testng.sample.TestcasesTest" name="testtopassTest1" time="0.046"/>
  <testcase classname="testng.sample.TestcasesTest" name="testtopassTest2" time="0.042"/>
  <testcase classname="testng.sample.TestcasesTest" name="testtofailTest1" time="0.004">
    <skipped/>
  </testcase> <!-- testtofailTest1 -->
  <testcase classname="testng.sample.TestcasesTest" name="testtopassTest4" time="0.042"/>
  <testcase classname="testng.sample.TestcasesTest" name="testtofailTest2" time="0.014">
    <skipped/>
  </testcase> <!-- testtofailTest2 -->
  <testcase classname="testng.sample.TestcasesTest" name="testtofailTest2" time="0.005">
    <skipped/>
  </testcase> <!-- testtofailTest2 -->
  <testcase classname="testng.sample.TestcasesTest" name="testtofailTest1" time="0.034">
    <skipped/>
  </testcase> <!-- testtofailTest1 -->
  <testcase classname="testng.sample.TestcasesTest" name="testtofailTest2" time="0.013">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testng.sample.TestcasesTest.testtofailTest2(TestcasesTest.java:49)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- testtofailTest2 -->
  <testcase classname="testng.sample.TestcasesTest" name="testtofailTest1" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testng.sample.TestcasesTest.testtofailTest1(TestcasesTest.java:42)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- testtofailTest1 -->
</testsuite> <!-- Test -->
