<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DV" failures="2" tests="12" name="Test" time="0.308" errors="0" timestamp="2021-05-26T23:12:37 IST">
  <testcase classname="testng.sample.TestcasesTest" name="testtopassTest1" time="0.036"/>
  <testcase classname="testng.sample.TestcasesTest" name="testtopassTest4" time="0.035"/>
  <testcase classname="testng.sample.TestcasesTest" name="testtopassTest2" time="0.05"/>
  <testcase classname="testng.sample.TestcasesTest" name="testtopassTest3" time="0.043"/>
  <testcase classname="testng.sample.TestcasesTest" name="testtofailTest2" time="0.047">
    <skipped/>
  </testcase> <!-- testtofailTest2 -->
  <testcase classname="testng.sample.TestcasesTest" name="testtofailTest1" time="0.047">
    <skipped/>
  </testcase> <!-- testtofailTest1 -->
  <testcase classname="testng.sample.TestcasesTest" name="testtofailTest2" time="0.012">
    <skipped/>
  </testcase> <!-- testtofailTest2 -->
  <testcase classname="testng.sample.TestcasesTest" name="testtofailTest2" time="0.006">
    <skipped/>
  </testcase> <!-- testtofailTest2 -->
  <testcase classname="testng.sample.TestcasesTest" name="testtofailTest1" time="0.016">
    <skipped/>
  </testcase> <!-- testtofailTest1 -->
  <testcase classname="testng.sample.TestcasesTest" name="testtofailTest1" time="0.005">
    <skipped/>
  </testcase> <!-- testtofailTest1 -->
  <testcase classname="testng.sample.TestcasesTest" name="testtofailTest2" time="0.005">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testng.sample.TestcasesTest.testtofailTest2(TestcasesTest.java:48)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- testtofailTest2 -->
  <testcase classname="testng.sample.TestcasesTest" name="testtofailTest1" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testng.sample.TestcasesTest.testtofailTest1(TestcasesTest.java:41)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- testtofailTest1 -->
</testsuite> <!-- Test -->
