<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DV" failures="2" tests="12" name="testng.sample.TestcasesTest" time="0.305" errors="0" timestamp="2021-05-26T23:12:37 IST" skipped="6">
  <testcase classname="testng.sample.TestcasesTest" name="testtofailTest2" time="0.047">
    <skipped/>
  </testcase> <!-- testtofailTest2 -->
  <system-out/>
  <testcase classname="testng.sample.TestcasesTest" name="testtopassTest3" time="0.043"/>
  <system-out/>
  <testcase classname="testng.sample.TestcasesTest" name="testtofailTest2" time="0.005">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at testng.sample.TestcasesTest.testtofailTest2(TestcasesTest.java:48)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- testtofailTest2 -->
  <system-out/>
  <testcase classname="testng.sample.TestcasesTest" name="testtofailTest2" time="0.012">
    <skipped/>
  </testcase> <!-- testtofailTest2 -->
  <system-out/>
  <testcase classname="testng.sample.TestcasesTest" name="testtofailTest1" time="0.016">
    <skipped/>
  </testcase> <!-- testtofailTest1 -->
  <system-out/>
  <testcase classname="testng.sample.TestcasesTest" name="testtofailTest1" time="0.005">
    <skipped/>
  </testcase> <!-- testtofailTest1 -->
  <system-out/>
  <testcase classname="testng.sample.TestcasesTest" name="testtofailTest1" time="0.003">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at testng.sample.TestcasesTest.testtofailTest1(TestcasesTest.java:41)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- testtofailTest1 -->
  <system-out/>
  <testcase classname="testng.sample.TestcasesTest" name="testtofailTest1" time="0.047">
    <skipped/>
  </testcase> <!-- testtofailTest1 -->
  <system-out/>
  <testcase classname="testng.sample.TestcasesTest" name="testtofailTest2" time="0.006">
    <skipped/>
  </testcase> <!-- testtofailTest2 -->
  <system-out/>
  <testcase classname="testng.sample.TestcasesTest" name="testtopassTest1" time="0.036"/>
  <system-out/>
  <testcase classname="testng.sample.TestcasesTest" name="testtopassTest4" time="0.035"/>
  <system-out/>
  <testcase classname="testng.sample.TestcasesTest" name="testtopassTest2" time="0.050"/>
  <system-out/>
</testsuite> <!-- testng.sample.TestcasesTest -->
